2017-11-10 09:06:07,295 [26] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_TestSet' 无效。
2017-11-10 09:06:07,310 [26] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_TestSet' 无效。
2017-11-10 10:04:43,037 [13] ERROR LeaRun.DataAccess.DbHelper - 列名 'testBegindDate' 无效。
2017-11-10 10:05:47,892 [7] ERROR LeaRun.DataAccess.DbHelper - 列名 'testBegindDate' 无效。
2017-11-10 10:10:04,527 [21] ERROR LeaRun.DataAccess.DbHelper - 列名 'testBegindDate' 无效。
2017-11-10 10:24:31,810 [9] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:24:38,284 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:24:39,322 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:24:39,539 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:24:39,773 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:24:44,258 [14] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:24:44,575 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:24:44,801 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:25:41,738 [12] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:25:43,243 [9] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:25:43,422 [12] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:25:43,600 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:28:11,258 [15] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
2017-11-10 10:30:21,868 [7] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestBeginDate nvarchar(10),@TestBeginWeek nvarchar(3),@TestAdd' 需要参数 '@ID'，但未提供该参数。
