2015-07-23 11:48:56,560 [6] ERROR LeaRun.DataAccess.DbHelper - 关键字 'FROM' 附近有语法错误。
2015-07-23 15:21:14,380 [8] ERROR LeaRun.DataAccess.DbHelper - 除非另外还指定了 TOP 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。
2015-07-23 15:21:22,683 [8] ERROR LeaRun.DataAccess.DbHelper - 除非另外还指定了 TOP 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。
2015-07-23 15:23:04,330 [8] ERROR LeaRun.DataAccess.DbHelper - 除非另外还指定了 TOP 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。
2015-07-23 15:26:09,503 [5] ERROR LeaRun.DataAccess.DbHelper - 除非另外还指定了 TOP 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。
2015-07-23 15:27:25,270 [10] ERROR LeaRun.DataAccess.DbHelper - 除非另外还指定了 TOP 或 FOR XML，否则，ORDER BY 子句在视图、内联函数、派生表、子查询和公用表表达式中无效。
