2017-11-14 10:23:48,694 [10] ERROR LeaRun.DataAccess.DbHelper - 列名 'TestSetID' 无效。
2017-11-14 10:25:34,295 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'TestSetID' 无效。
2017-11-14 15:31:22,604 [10] ERROR LeaRun.DataAccess.DbHelper - 列名 'TestGroupCode' 无效。
2017-11-14 15:33:52,259 [7] ERROR LeaRun.DataAccess.DbHelper - 列名 'TestGroupCode' 无效。
2017-11-14 16:03:23,570 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@AllotState"。
2017-11-14 16:04:03,824 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@AllotState"。
