2018-05-26 11:23:03,676 [17] ERROR LeaRun.DataAccess.DbHelper - Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
2018-05-26 11:23:03,676 [11] ERROR LeaRun.DataAccess.DbHelper - Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
2018-05-26 11:23:03,676 [16] ERROR LeaRun.DataAccess.DbHelper - Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
2018-05-26 20:53:05,756 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@EightHundred'，但未提供该参数。
2018-05-26 20:53:07,912 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@ThousandRun'，但未提供该参数。
2018-05-26 20:55:05,812 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@EightHundred'，但未提供该参数。
2018-05-26 20:55:10,404 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@ThousandRun'，但未提供该参数。
2018-05-26 21:00:02,431 [17] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@EightHundredAddScore'，但未提供该参数。
2018-05-26 21:00:07,373 [17] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@ThousandRun'，但未提供该参数。
2018-05-26 21:02:02,637 [29] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@EightHundred'，但未提供该参数。
2018-05-26 21:02:57,801 [29] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@ThousandRun'，但未提供该参数。
