2017-10-27 14:04:19,064 [8] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:04:25,696 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:04:27,785 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:04:28,678 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:07:27,422 [8] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:09:20,927 [7] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:09:41,207 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:11:59,104 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:13:00,894 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:14:07,388 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:20:06,250 [7] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@DStudent_Announcement"。
2017-10-27 14:22:36,924 [8] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@tableName"。
2017-10-27 14:27:45,843 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@tableName"。
2017-10-27 14:37:01,082 [10] ERROR LeaRun.DataAccess.DbHelper - 'd' 附近有语法错误。
2017-10-27 14:45:00,635 [8] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@tableName"。
2017-10-27 14:52:11,768 [8] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WHERE' 附近有语法错误。
2017-10-27 15:00:48,119 [18] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WHERE' 附近有语法错误。
2017-10-27 15:00:53,487 [16] ERROR LeaRun.DataAccess.DbHelper - 关键字 'WHERE' 附近有语法错误。
2017-10-27 15:16:33,876 [5] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:06,252 [5] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:08,933 [5] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:09,656 [5] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:10,078 [8] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:10,890 [6] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:12,158 [5] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:12,923 [9] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 15:43:45,584 [5] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 16:56:56,206 [52] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 16:57:07,025 [40] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 17:16:18,072 [6] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 17:16:51,649 [6] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-27 17:18:12,155 [10] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
