2017-11-06 15:37:59,181 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000),@StudentName nvarchar(4000),@Studen' 需要参数 '@ThousandRunAddScore'，但未提供该参数。
2017-11-06 15:38:00,432 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000),@StudentName nvarchar(4000),@Studen' 需要参数 '@ThousandRunAddScore'，但未提供该参数。
2017-11-06 17:22:48,876 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@TestResult'，但未提供该参数。
2017-11-06 17:22:50,273 [15] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@TestResult'，但未提供该参数。
2017-11-06 17:29:07,951 [21] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@TestResult'，但未提供该参数。
2017-11-06 17:49:50,524 [9] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000),@StudentName nvarchar(4000),@Studen' 需要参数 '@TestResult'，但未提供该参数。
2017-11-06 17:52:33,885 [9] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@MinSupinationAddScore'，但未提供该参数。
2017-11-06 17:54:49,675 [9] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@TestResult'，但未提供该参数。
2017-11-06 17:54:57,293 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@TestResult'，但未提供该参数。
2017-11-06 17:55:11,067 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@TestResult'，但未提供该参数。
2017-11-06 17:57:02,971 [7] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@TestType"。
