2017-11-16 09:11:47,395 [24] ERROR LeaRun.DataAccess.DbHelper - 关键字 'where' 附近有语法错误。
'=' 附近有语法错误。
2017-11-16 11:44:43,573 [54] ERROR LeaRun.DataAccess.DbHelper - 列名 '约考测试' 无效。
2017-11-16 11:44:52,221 [32] ERROR LeaRun.DataAccess.DbHelper - 列名 '约考测试' 无效。
2017-11-16 11:44:52,530 [55] ERROR LeaRun.DataAccess.DbHelper - 列名 '约考测试' 无效。
2017-11-16 11:44:52,698 [52] ERROR LeaRun.DataAccess.DbHelper - 列名 '约考测试' 无效。
2017-11-16 11:44:59,763 [46] ERROR LeaRun.DataAccess.DbHelper - 列名 '约考测试' 无效。
2017-11-16 11:46:26,785 [5] ERROR LeaRun.DataAccess.DbHelper - 列名 '约考测试' 无效。
2017-11-16 17:02:23,518 [5] ERROR LeaRun.DataAccess.DbHelper - 'ApplyFor' 附近有语法错误。
2017-11-16 17:04:17,299 [11] ERROR LeaRun.DataAccess.DbHelper - 'ApplyFor' 附近有语法错误。
2017-11-16 17:05:36,639 [11] ERROR LeaRun.DataAccess.DbHelper - 'ApplyFor' 附近有语法错误。
2017-11-16 17:16:37,713 [34] ERROR LeaRun.DataAccess.DbHelper - 'ApplyFor' 附近有语法错误。
2017-11-16 17:16:56,003 [25] ERROR LeaRun.DataAccess.DbHelper - 'ApplyFor' 附近有语法错误。
2017-11-16 17:18:41,277 [5] ERROR LeaRun.DataAccess.DbHelper - 'and' 附近有语法错误。
