2018-06-08 07:18:29,059 [98] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'SELECT * from DBase_Users where ID=@ID'。
2018-06-08 07:20:48,652 [105] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'SELECT * from DBase_Users where ID=@IDDelete from DBase_Users where ID=@ID'。
2018-06-08 07:21:24,226 [109] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'Delete from DBase_Users where ID=@ID'。
2018-06-08 07:22:08,024 [105] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'Delete from DBase_Users where ID=@ID'。
2018-06-08 07:23:13,072 [108] ERROR LeaRun.DataAccess.DbHelper - 找不到存储过程 'Delete DBase_Users where ID=@ID'。
