2017-11-07 14:40:06,996 [19] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_MarkFree' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-07 14:40:11,928 [20] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_MarkFree' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-07 14:40:18,113 [19] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_MarkFree' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-07 14:40:39,376 [11] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_MarkFree' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-07 14:41:54,565 [5] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_MarkFree' 需要参数 '@StudentCode'，但未提供该参数。
