2018-05-07 11:57:12,646 [29] ERROR LeaRun.DataAccess.DbHelper - 列名 'BigtTwo' 无效。
列名 'CreateTime' 无效。
列名 'Remark' 无效。
2018-05-07 12:00:46,251 [30] ERROR LeaRun.DataAccess.DbHelper - 列名 'BigtTwo' 无效。
列名 'CreateTime' 无效。
列名 'Remark' 无效。
2018-05-07 12:09:20,940 [33] ERROR LeaRun.DataAccess.DbHelper - 列名 'CreateTime' 无效。
列名 'Remark' 无效。
2018-05-07 12:09:26,457 [24] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:09:29,528 [27] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:09:53,040 [36] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:14:30,701 [6] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:14:34,777 [6] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:14:38,796 [38] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:14:42,858 [6] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:16:44,731 [17] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:16:47,835 [28] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:16:51,197 [33] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:16:54,891 [6] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:16:58,895 [6] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:19:55,197 [33] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:19:58,753 [14] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:23:29,333 [46] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:23:37,249 [46] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:23:42,441 [47] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:24:27,243 [48] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:27:02,178 [9] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:27:07,701 [8] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:29:29,384 [10] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:29:41,326 [19] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:33:04,069 [19] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:33:07,170 [19] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:33:10,451 [16] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:33:15,607 [17] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:34:52,447 [19] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:36:05,391 [13] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:36:34,171 [19] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:37:51,133 [23] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:45:37,235 [5] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:46:04,011 [13] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:47:40,994 [25] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 12:50:32,184 [26] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:03:10,173 [52] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:03:40,083 [41] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:03:58,598 [43] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:04:12,679 [43] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:04:20,031 [52] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:05:03,527 [44] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:05:31,687 [49] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:06:29,171 [49] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:06:41,714 [57] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentSex"。
2018-05-07 13:42:03,829 [38] ERROR LeaRun.DataAccess.DbHelper - 列名 'CreateTime' 无效。
列名 'Remark' 无效。
2018-05-07 13:44:42,610 [38] ERROR LeaRun.DataAccess.DbHelper - “=”附近有语法错误。
2018-05-07 13:46:51,652 [23] ERROR LeaRun.DataAccess.DbHelper - “=”附近有语法错误。
2018-05-07 13:48:59,768 [25] ERROR LeaRun.DataAccess.DbHelper - “=”附近有语法错误。
2018-05-07 13:50:36,651 [26] ERROR LeaRun.DataAccess.DbHelper - “=”附近有语法错误。
2018-05-07 14:40:25,362 [30] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentCode"。
2018-05-07 14:41:03,102 [30] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentCode"。
2018-05-07 14:41:55,256 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000),@FinshTest nvarchar(4),@FinshYear n' 需要参数 '@StudentCode'，但未提供该参数。
2018-05-07 14:42:28,758 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000),@FinshTest nvarchar(4),@FinshYear n' 需要参数 '@StudentCode'，但未提供该参数。
2018-05-07 14:56:22,475 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(10),@StudentName nvarchar(3),@StudentSex ' 需要参数 '@EightHundred'，但未提供该参数。
