2017-11-13 17:49:40,472 [10] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_TestAllot2017' 无效。
2017-11-13 17:50:54,729 [12] ERROR LeaRun.DataAccess.DbHelper - INSERT 语句的选择列表包含的项少于插入列表中的项。SELECT 语句中值的数目必须与 INSERT 语句中列的数目匹配。
2017-11-13 17:54:26,775 [8] ERROR LeaRun.DataAccess.DbHelper - INSERT 语句的选择列表包含的项少于插入列表中的项。SELECT 语句中值的数目必须与 INSERT 语句中列的数目匹配。
2017-11-13 17:56:03,688 [9] ERROR LeaRun.DataAccess.DbHelper - INSERT 语句的选择列表包含的项少于插入列表中的项。SELECT 语句中值的数目必须与 INSERT 语句中列的数目匹配。
2017-11-13 17:57:12,833 [11] ERROR LeaRun.DataAccess.DbHelper - INSERT 语句的选择列表包含的项少于插入列表中的项。SELECT 语句中值的数目必须与 INSERT 语句中列的数目匹配。
