2017-11-17 09:57:57,662 [125] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 09:57:59,177 [122] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 09:57:59,889 [122] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 09:58:00,703 [127] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 09:58:00,931 [128] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 09:58:01,099 [127] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 09:58:01,287 [122] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 09:59:24,359 [9] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 10:00:34,065 [10] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 10:00:44,984 [10] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 10:02:36,576 [10] ERROR LeaRun.DataAccess.DbHelper - 关键字 'AND' 附近有语法错误。
2017-11-17 10:43:10,419 [58] ERROR LeaRun.DataAccess.DbHelper - 将截断字符串或二进制数据。
语句已终止。
