2017-11-29 10:20:40,940 [14] ERROR LeaRun.DataAccess.DbHelper - 无法绑定由多个部分组成的标识符 "d.className"。
无法绑定由多个部分组成的标识符 "d.StudentSex"。
无法绑定由多个部分组成的标识符 "d.testTeacher"。
无法绑定由多个部分组成的标识符 "d.applyFor"。
无法绑定由多个部分组成的标识符 "d.studentCode"。
无法绑定由多个部分组成的标识符 "d.gradeCode"。
列名 'object HTMLInputElement' 无效。
2017-11-29 10:23:13,541 [8] ERROR LeaRun.DataAccess.DbHelper - 列名 'object HTMLInputElement' 无效。
2017-11-29 10:26:09,153 [9] ERROR LeaRun.DataAccess.DbHelper - 列名 'object HTMLInputElement' 无效。
2017-11-29 10:32:01,137 [14] ERROR LeaRun.DataAccess.DbHelper - 列名 't' 无效。
2017-11-29 10:32:40,593 [18] ERROR LeaRun.DataAccess.DbHelper - 列名 'testt' 无效。
