2018-05-10 19:02:58,826 [29] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_AddDStudentInfoImport' 需要参数 '@GradeCode'，但未提供该参数。
2018-05-10 19:03:07,634 [29] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_AddDStudentInfoImport' 需要参数 '@GradeCode'，但未提供该参数。
2018-05-10 19:03:07,637 [29] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_AddDStudentInfoImport' 需要参数 '@GradeCode'，但未提供该参数。
2018-05-10 19:18:37,070 [28] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_AddDStudentInfoImport' 需要参数 '@CreateTime'，但未提供该参数。
2018-05-10 19:19:35,284 [28] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_AddDStudentInfoImport' 需要参数 '@CreateTime'，但未提供该参数。
2018-05-10 19:19:35,297 [28] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_AddDStudentInfoImport' 需要参数 '@CreateTime'，但未提供该参数。
