2018-05-05 12:43:56,565 [113] ERROR LeaRun.DataAccess.DbHelper - 列名或所提供值的数目与表定义不匹配。
2018-05-05 12:47:14,089 [120] ERROR LeaRun.DataAccess.DbHelper - 列名或所提供值的数目与表定义不匹配。
2018-05-05 13:22:46,314 [49] ERROR LeaRun.DataAccess.DbHelper - 列名或所提供值的数目与表定义不匹配。
2018-05-05 13:37:23,070 [10] ERROR LeaRun.DataAccess.DbHelper - 在将 nvarchar 值 '10,14' 转换成数据类型 int 时失败。
2018-05-05 13:37:47,778 [8] ERROR LeaRun.DataAccess.DbHelper - 在将 nvarchar 值 '10,14' 转换成数据类型 int 时失败。
2018-05-05 13:42:33,411 [9] ERROR LeaRun.DataAccess.DbHelper - “StudentName”附近有语法错误。
2018-05-05 13:42:42,638 [8] ERROR LeaRun.DataAccess.DbHelper - “StudentName”附近有语法错误。
2018-05-05 13:43:06,756 [9] ERROR LeaRun.DataAccess.DbHelper - “StudentName”附近有语法错误。
2018-05-05 13:46:11,070 [13] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Test@NK' 无效。
2018-05-05 13:49:59,790 [25] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@TName"。
2018-05-05 13:50:13,489 [22] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@TName"。
2018-05-05 13:51:43,579 [26] ERROR LeaRun.DataAccess.DbHelper - 必须声明表变量 "@TName"。
2018-05-05 13:52:46,563 [26] ERROR LeaRun.DataAccess.DbHelper - 对象名 '@TName' 无效。
2018-05-05 13:52:58,172 [21] ERROR LeaRun.DataAccess.DbHelper - 对象名 '@TName' 无效。
2018-05-05 14:15:31,676 [5] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Test@NK' 无效。
2018-05-05 18:27:38,515 [15] ERROR LeaRun.DataAccess.DbHelper - 列名 'testBeginDate' 无效。
2018-05-05 18:27:51,290 [41] ERROR LeaRun.DataAccess.DbHelper - 列名 'testBeginDate' 无效。
2018-05-05 18:28:56,416 [41] ERROR LeaRun.DataAccess.DbHelper - 列名 'testBeginDate' 无效。
