2017-11-01 11:38:18,349 [6] ERROR LeaRun.DataAccess.DbHelper - 列名 'GradeCode' 无效。
列名 'SchoolName' 无效。
列名 'SchoolCode' 无效。
2017-11-01 11:40:27,712 [11] ERROR LeaRun.DataAccess.DbHelper - 列名 'GradeCode' 无效。
列名 'SchoolName' 无效。
列名 'SchoolCode' 无效。
2017-11-01 11:41:15,820 [15] ERROR LeaRun.DataAccess.DbHelper - 列名 'GradeCode' 无效。
列名 'SchoolName' 无效。
列名 'SchoolCode' 无效。
2017-11-01 13:31:01,007 [21] ERROR LeaRun.DataAccess.DbHelper - 列名 'GradeCode' 无效。
列名 'SchoolName' 无效。
列名 'SchoolCode' 无效。
2017-11-01 13:33:31,985 [20] ERROR LeaRun.DataAccess.DbHelper - 列名 'GradeCode' 无效。
列名 'SchoolName' 无效。
列名 'SchoolCode' 无效。
2017-11-01 14:42:12,251 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@SchoolCode nvarchar(4000))SELECT DISTINCT ClassName,ClassCode ' 需要参数 '@SchoolCode'，但未提供该参数。
2017-11-01 15:18:20,018 [21] ERROR LeaRun.DataAccess.DbHelper - '`' 附近有语法错误。
2017-11-01 15:19:32,871 [13] ERROR LeaRun.DataAccess.DbHelper - '`' 附近有语法错误。
2017-11-01 15:20:24,560 [9] ERROR LeaRun.DataAccess.DbHelper - '`' 附近有语法错误。
2017-11-01 15:22:38,330 [5] ERROR LeaRun.DataAccess.DbHelper - '`' 附近有语法错误。
2017-11-01 15:24:38,807 [10] ERROR LeaRun.DataAccess.DbHelper - '`' 附近有语法错误。
2017-11-01 15:26:38,882 [9] ERROR LeaRun.DataAccess.DbHelper - '`' 附近有语法错误。
2017-11-01 15:28:28,087 [5] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentTrueScore"。
2017-11-01 15:50:17,831 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000))SELECT * FROM DStudent_Infos2017 WH' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-01 15:50:51,134 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000))SELECT * FROM DStudent_Infos2017 WH' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-01 15:51:36,695 [14] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000))SELECT * FROM DStudent_Infos2017 WH' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-01 15:51:51,600 [14] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000))SELECT * FROM DStudent_Infos2017 WH' 需要参数 '@StudentCode'，但未提供该参数。
2017-11-01 15:52:35,482 [11] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@StudentCode nvarchar(4000))SELECT * FROM DStudent_Infos2017 WH' 需要参数 '@StudentCode'，但未提供该参数。
