2018-05-14 16:15:45,685 [185] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@UserPassword nvarchar(4000),@UserCode nvarchar(6),@UpdateTime ' 需要参数 '@UserPassword'，但未提供该参数。
2018-05-14 16:34:23,513 [211] ERROR LeaRun.DataAccess.DbHelper - 关键字 'into' 附近有语法错误。
2018-05-14 19:47:39,653 [10] ERROR LeaRun.DataAccess.DbHelper - 列名 'Remark' 无效。
2018-05-14 19:48:45,233 [6] ERROR LeaRun.DataAccess.DbHelper - 列名 'Remark' 无效。
2018-05-14 19:54:36,200 [14] ERROR LeaRun.DataAccess.DbHelper - 变量名 '@CreateUser' 已声明。变量名在查询批次或存储过程内部必须唯一。
2018-05-14 20:03:48,187 [17] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:50,020 [10] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:51,370 [18] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:52,128 [20] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:52,505 [18] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:52,699 [20] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:52,868 [17] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:53,081 [20] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:53,416 [14] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:53,741 [17] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:03:55,180 [17] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:10,865 [17] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:11,609 [10] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:11,767 [10] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:12,100 [17] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:12,244 [20] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:12,427 [14] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:12,573 [17] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:12,735 [20] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:12,888 [14] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
2018-05-14 20:04:13,040 [20] ERROR LeaRun.DataAccess.DbHelper - 无法对 表 'DStudent_Announcement2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Class2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Infos2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_Test2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestAllot2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScore2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestScoreLog2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DStudent_TestSet2016' 执行 删除，因为它不存在，或者您没有所需的权限。
无法对 表 'DTecher_TestOnOff2016' 执行 删除，因为它不存在，或者您没有所需的权限。
