2017-10-30 09:10:51,359 [7] ERROR LeaRun.DataAccess.DbHelper - 'DStudent_Announcement2017' 附近有语法错误。
2017-10-30 09:20:46,403 [13] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-30 09:20:46,416 [13] ERROR LeaRun.DataAccess.DbHelper - 对象名 'DStudent_Announcement' 无效。
2017-10-30 10:17:55,149 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:17:57,750 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:17:58,150 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:17:58,363 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:17:59,417 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:17:59,630 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:18:00,558 [9] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:18:00,764 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:18:01,570 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:18:01,783 [6] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(2),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:35:53,114 [36] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(5),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:35:56,047 [36] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(5),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:36:56,727 [14] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(7),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:37:43,300 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(6),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:37:43,841 [9] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(6),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:37:44,059 [7] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(6),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:37:44,274 [10] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(6),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:37:44,486 [7] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(6),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
2017-10-30 10:39:26,346 [5] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@Title nvarchar(4000),@Content nvarchar(3),@ContentState nvarch' 需要参数 '@Title'，但未提供该参数。
