2017-11-15 09:37:28,338 [17] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@ID"。
2017-11-15 09:38:30,735 [15] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@ID"。
2017-11-15 17:03:25,839 [8] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@TestSetID nvarchar(4000))SELECT * FROM DStudent_TestAllot WHER' 需要参数 '@TestSetID'，但未提供该参数。
2017-11-15 17:18:32,633 [21] ERROR LeaRun.DataAccess.DbHelper - 过程或函数 'Proc_AddDStudentTestAdmin' 需要参数 '@TestTeacher'，但未提供该参数。
2017-11-15 17:21:00,243 [13] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentCode"。
2017-11-15 17:22:10,543 [13] ERROR LeaRun.DataAccess.DbHelper - 必须声明标量变量 "@StudentCode"。
2017-11-15 17:23:53,917 [15] ERROR LeaRun.DataAccess.DbHelper - 在将 varchar 值 'insert into dbo.DStudent_Test2017(StudentCode,GradeCode,SchoolCode,SchoolName,ClassCode,ClassName,TestSetID,StudentName,StudentSex,TestTeacher,TestAddress,
BeginPraDate,BeginWeek,BeginPraTime,ApplyFor,TestGroup,TestGroupCode,TestType,CreateTime,UpdateTime,Remark)values(2013010706,44,4404,教育学院,440401,13教育学1班,' 转换成数据类型 int 时失败。
2017-11-15 17:23:58,769 [15] ERROR LeaRun.DataAccess.DbHelper - 在将 varchar 值 'insert into dbo.DStudent_Test2017(StudentCode,GradeCode,SchoolCode,SchoolName,ClassCode,ClassName,TestSetID,StudentName,StudentSex,TestTeacher,TestAddress,
BeginPraDate,BeginWeek,BeginPraTime,ApplyFor,TestGroup,TestGroupCode,TestType,CreateTime,UpdateTime,Remark)values(2013010706,44,4404,教育学院,440401,13教育学1班,' 转换成数据类型 int 时失败。
2017-11-15 17:28:01,344 [9] ERROR LeaRun.DataAccess.DbHelper - 在将 varchar 值 'insert into dbo.DStudent_Test2017(StudentCode,GradeCode,SchoolCode,SchoolName,ClassCode,ClassName,TestSetID,StudentName,StudentSex,TestTeacher,TestAddress,
BeginPraDate,BeginWeek,BeginPraTime,ApplyFor,TestGroup,TestGroupCode,TestType,CreateTime,UpdateTime,Remark)values(2013010706,44,4404,教育学院,440401,13教育学1班,' 转换成数据类型 int 时失败。
