2017-10-26 10:30:44,217 [30] ERROR LeaRun.DataAccess.DbHelper - 各表中的列名必须唯一。在表 'DStudent_TestScore' 中多次指定了列名 'FiftyRunLevel'。
2017-10-26 17:41:41,057 [13] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2017-10-26 17:41:49,517 [14] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2017-10-26 17:42:10,759 [16] ERROR LeaRun.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
